### ISSUE TITLE
ขอชม

### ISSUE THREAD

**Issue by Bancherd-DeLong** [PyThaiNLP/spaCy-th#2]
นับถือครับ  มีใครช่วยบ้างมั้ยครับ?  ตัวผมเองไม่รู้เรื่องเลย ตอนนี้กำลังลองเล่น ASR แบบ hobby ครับ

**Comment by wannaphong** [comment]
มีคุณ @korakot ช่วยครับ และกลุ่ม Thai natural language processing https://www.facebook.com/groups/408004796247683/ ครับ
